### ISSUE TITLE
needs tests

### ISSUE THREAD

**Issue by aspiers** [openSUSE/github-pr#2]
The code looks pretty nice, but pleeeease consider adopting TDD/BDD ;-)  It's more fun, honest!

**Comment by jdsn** [comment]
Added rspec tests for all included filters.

**Comment by aspiers** [comment]
@jdsn Very cool, thanks!  BTW don't forget you can use this trick to auto-close issues :-) https://help.github.com/articles/closing-issues-using-keywords/

It's helpful for keeping it clear which PRs/commits closed an issue.

**Comment by jdsn** [comment]
thanks for the hint
